version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    networks:
      - backend

  db:
    image: sqlite:3.32.3
    volumes:
      - db_data:/var/lib/sqlite3
    networks:
      - backend

  api-gateway:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge
